sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install tox-travis
  - pip install -r requirements-test.text
script:
  - tox -r
after_success:
  - coverage report
  - coveralls
